### ISSUE TITLE
Modifica del file markdown Guida per lo studente.md, personalizzando le figure in cui compare un nome di repository diverso dal proprio

### ISSUE THREAD

**Issue by Rikoo11** [softeng2223-inf-uniba/progetto2223-naur#5]
Modificare il file markdown Guida per lo _studente.md_, personalizzando le figure in cui compare un nome di repository diverso dal proprio, oppure uno username o immagine di profilo diverso da quello dei componenti del gruppo.

**Comment by LuanNurja02** [comment]
Modifiche effettuate, bravo !
